# Stage 1: Build
FROM node:20-alpine AS build
WORKDIR /app
ARG VITE_STRIPE_PUBLISHABLE_KEY
ARG VITE_AUTH_URL
ARG VITE_CART_URL
ARG VITE_ORDER_URL
ARG VITE_PAYMENT_URL
ARG VITE_PRODUCT_URL
ARG VITE_CATEGORY_URL
ENV VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY
ENV VITE_AUTH_URL=$VITE_AUTH_URL
ENV VITE_CART_URL=$VITE_CART_URL
ENV VITE_ORDER_URL=$VITE_ORDER_URL
ENV VITE_PAYMENT_URL=$VITE_PAYMENT_URL
ENV VITE_PRODUCT_URL=$VITE_PRODUCT_URL
ENV VITE_CATEGORY_URL=$VITE_CATEGORY_URL
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve
FROM nginx:stable-alpine

# 1. Copy the built files
# (Check if your build output is in 'dist' or 'build')
COPY --from=build /app/dist /usr/share/nginx/html

# 2. COPY YOUR CUSTOM NGINX CONFIG (Crucial Step)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
