"""message

Revision ID: 56f9f86cc8ec
Revises: 4b8a0d0a14e3
Create Date: 2025-11-21 13:25:13.717997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f9f86cc8ec'
down_revision: Union[str, None] = '4b8a0d0a14e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_payment_stripe_payment_intent_id'), 'payment', ['stripe_payment_intent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_stripe_payment_intent_id'), table_name='payment')
    op.drop_column('payment', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
