"""Added price_at_purchase

Revision ID: a5bde424ef9e
Revises: e5e5bbdcf03b
Create Date: 2025-11-17 11:19:46.512733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5bde424ef9e'
down_revision: Union[str, None] = 'e5e5bbdcf03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'price_at_purchase')
    # ### end Alembic commands ###
