"""Description of migration

Revision ID: d85c2964ec32
Revises: 3cf6a313cad2
Create Date: 2025-11-20 23:28:26.570759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85c2964ec32'
down_revision: Union[str, None] = '3cf6a313cad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('admin_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'admin_id')
    # ### end Alembic commands ###
