"""Initial migration

Revision ID: 739a6df20840
Revises: a51d075daf06
Create Date: 2025-11-12 17:43:54.931514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '739a6df20840'
down_revision: Union[str, None] = 'a51d075daf06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.JSON(), nullable=True))
    op.drop_column('products', 'Image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Image_path', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###
