"""your message

Revision ID: 5cff7608696d
Revises: a82c2269921b
Create Date: 2025-11-18 17:39:28.747508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cff7608696d'
down_revision: Union[str, None] = 'a82c2269921b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_Goverment_ID', table_name='admins')
    op.create_index(op.f('ix_admins_Goverment_ID'), 'admins', ['Goverment_ID'], unique=False)
    op.create_unique_constraint(None, 'admins', ['Id_Number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_index(op.f('ix_admins_Goverment_ID'), table_name='admins')
    op.create_index('ix_admins_Goverment_ID', 'admins', ['Goverment_ID'], unique=True)
    # ### end Alembic commands ###
