"""Descriptive message for the migration

Revision ID: 62b1d28ff4fa
Revises: 5cff7608696d
Create Date: 2025-11-19 16:00:34.103068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b1d28ff4fa'
down_revision: Union[str, None] = '5cff7608696d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('Mobile_Number', sa.String(), nullable=True))
    op.drop_index('ix_admins_Moblile_Number', table_name='admins')
    op.create_index(op.f('ix_admins_Mobile_Number'), 'admins', ['Mobile_Number'], unique=True)
    op.drop_column('admins', 'Moblile_Number')
    op.add_column('users', sa.Column('Mobile_Number', sa.String(), nullable=True))
    op.drop_index('ix_users_Moblile_Number', table_name='users')
    op.create_index(op.f('ix_users_Mobile_Number'), 'users', ['Mobile_Number'], unique=True)
    op.drop_column('users', 'Moblile_Number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Moblile_Number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_Mobile_Number'), table_name='users')
    op.create_index('ix_users_Moblile_Number', 'users', ['Moblile_Number'], unique=True)
    op.drop_column('users', 'Mobile_Number')
    op.add_column('admins', sa.Column('Moblile_Number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_admins_Mobile_Number'), table_name='admins')
    op.create_index('ix_admins_Moblile_Number', 'admins', ['Moblile_Number'], unique=True)
    op.drop_column('admins', 'Mobile_Number')
    # ### end Alembic commands ###
