"""Initial migration

Revision ID: 7f714e61660a
Revises: 
Create Date: 2025-11-12 17:15:10.198872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f714e61660a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Moblile_Number', sa.Integer(), nullable=True),
    sa.Column('Goverment_ID', sa.Integer(), nullable=True),
    sa.Column('Id_proof_path', sa.String(), nullable=False),
    sa.Column('GST_Number', sa.Integer(), nullable=True),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_Email'), 'admins', ['Email'], unique=True)
    op.create_index(op.f('ix_admins_GST_Number'), 'admins', ['GST_Number'], unique=True)
    op.create_index(op.f('ix_admins_Goverment_ID'), 'admins', ['Goverment_ID'], unique=True)
    op.create_index(op.f('ix_admins_Moblile_Number'), 'admins', ['Moblile_Number'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_name'), 'admins', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Moblile_Number', sa.Integer(), nullable=True),
    sa.Column('Password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_Moblile_Number'), 'users', ['Moblile_Number'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_Moblile_Number'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_admins_name'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_Moblile_Number'), table_name='admins')
    op.drop_index(op.f('ix_admins_Goverment_ID'), table_name='admins')
    op.drop_index(op.f('ix_admins_GST_Number'), table_name='admins')
    op.drop_index(op.f('ix_admins_Email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
