"""sync models

Revision ID: a82c2269921b
Revises: 2799b5657842
Create Date: 2025-11-17 17:49:33.269157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82c2269921b'
down_revision: Union[str, None] = '2799b5657842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Moblile_Number', sa.String(), nullable=True),
    sa.Column('Goverment_ID', sa.String(), nullable=True),
    sa.Column('Id_Number', sa.String(), nullable=False),
    sa.Column('GST_Number', sa.String(), nullable=True),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_Email'), 'admins', ['Email'], unique=True)
    op.create_index(op.f('ix_admins_GST_Number'), 'admins', ['GST_Number'], unique=True)
    op.create_index(op.f('ix_admins_Goverment_ID'), 'admins', ['Goverment_ID'], unique=True)
    op.create_index(op.f('ix_admins_Moblile_Number'), 'admins', ['Moblile_Number'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_name'), 'admins', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_name'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_Moblile_Number'), table_name='admins')
    op.drop_index(op.f('ix_admins_Goverment_ID'), table_name='admins')
    op.drop_index(op.f('ix_admins_GST_Number'), table_name='admins')
    op.drop_index(op.f('ix_admins_Email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
