"""add is_superuser to admins

Revision ID: b8968d9248e2
Revises: cf056d2d9bed
Create Date: 2025-11-10 13:27:22.567024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8968d9248e2'
down_revision: Union[str, Sequence[str], None] = 'cf056d2d9bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.alter_column('users', 'Moblile_Number',
               existing_type=sa.BigInteger(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Moblile_Number',
               existing_type=sa.BigInteger(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('admins', 'is_superuser')
    # ### end Alembic commands ###
