"""Description of model changes

Revision ID: cf056d2d9bed
Revises: 2aec5bf0d4f5
Create Date: 2025-11-07 12:59:10.976833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf056d2d9bed'
down_revision: Union[str, Sequence[str], None] = '2aec5bf0d4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Moblile_Number', sa.Integer(), nullable=True),
    sa.Column('Goverment_ID', sa.Integer(), nullable=True),
    sa.Column('Id_proof_path', sa.String(), nullable=False),
    sa.Column('GST_Number', sa.Integer(), nullable=True),
    sa.Column('Password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_Email'), 'admins', ['Email'], unique=True)
    op.create_index(op.f('ix_admins_GST_Number'), 'admins', ['GST_Number'], unique=True)
    op.create_index(op.f('ix_admins_Goverment_ID'), 'admins', ['Goverment_ID'], unique=True)
    op.create_index(op.f('ix_admins_Moblile_Number'), 'admins', ['Moblile_Number'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_name'), 'admins', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Moblile_Number', sa.Integer(), nullable=True),
    sa.Column('Password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_Moblile_Number'), 'users', ['Moblile_Number'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_Moblile_Number'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_admins_name'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_Moblile_Number'), table_name='admins')
    op.drop_index(op.f('ix_admins_Goverment_ID'), table_name='admins')
    op.drop_index(op.f('ix_admins_GST_Number'), table_name='admins')
    op.drop_index(op.f('ix_admins_Email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
